name: HOYYS
favicon: null
layout_spectrum: 0.9575561108067632
typography_spectrum: 0.7205092678777874
title: H O Y Y S
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-78765043-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9642656550277025
  lightness: 0.8766242333222181
  saturation: 0.6775692910887301
  rhythmicContrast: 0.7656843236181885
purpose: []
